### PR TITLE
feat(@vortex-demo-embark): Add support for Embark 4.0.0

### PR DESCRIPTION
**Pull request by emizzle**
Add support for Embark 4.0.0 and bump version.
Remove package.lock as it was conflicting with Embark's peer dependencies. 

### Known issues
`npm install` works, however errors during the `postinstall` (which runs `tsc`) of the `vort_x@1.1.3` package:
```
> vort_x@1.1.3 postinstall /Users/emizzle/temp/templates/vortex-template/node_modules/vort_x
> tsc

_sources/sources/contracts/contracts.saga.ts:29:9 - error TS2305: Module '"/Users/emizzle/temp/templates/vortex-template/node_modules/@types/bn.js/index"' has no exported member 'BN'.

29 import {BN} from 'bn.js';
           ~~


_sources/sources/contracts/contracts.saga.ts:29:18 - error TS2497: Module '"/Users/emizzle/temp/templates/vortex-template/node_modules/@types/bn.js/index"' resolves to a non-module entity and cannot be imported using this construct.

29 import {BN} from 'bn.js';
                    ~~~~~~~


_sources/sources/tx/tx.sagas.ts:15:9 - error TS2305: Module '"/Users/emizzle/temp/templates/vortex-template/node_modules/@types/bn.js/index"' has no exported member 'BN'.

15 import {BN} from 'bn.js';
           ~~


_sources/sources/tx/tx.sagas.ts:15:18 - error TS2497: Module '"/Users/emizzle/temp/templates/vortex-template/node_modules/@types/bn.js/index"' resolves to a non-module entity and cannot be imported using this construct.

15 import {BN} from 'bn.js';
                    ~~~~~~~
```

### CODE REVIEW

**Comment by mortimr** [comment]
Hi @emizzle, thank you for your contribution !
I am currently reworking vortex from the ground up , and this issue is currently fixed.

I am sorry, I should have written somewhere that the project is having massive upgrades.

Are you using vortex in your projects ?

**Comment by emizzle** [comment]
I am a core contributor for Embark, and we are getting ready to release version 4.0.0. Since Vortex is listed as a [template we support](https://embark.status.im/templates/), I was pushing an update so that the template wouldn't break with the latest major release of embark.

**Comment by mortimr** [comment]
Ok  👍 !
I didn't knew the repository was listed there. I will update you on the next release as soon as I finish it and make a template for embark.

**Comment by emizzle** [comment]
Thanks @mortimr, looking forward to the updates!

**Pull request merged**
